### ISSUE TITLE
How to develop the code and add other tricks?

### ISSUE THREAD

**Issue by hikaru-nara** [allenai/dont-stop-pretraining#12]
Hi, thank you for the interesting work!
I understand that an interface is provided by the conda packages and the conda environment, which is very convenient for reproducing results. Now I desire to develop the code and add other tricks to the model. Is there a natural way to do so? I mean I can definitely dig into the conda packages and work on them but that's against common develop habits...

**Comment by kernelmachine** [comment]
Hi there,

you can fork this repository and improve on code related to downstream tasks with AllenNLP, or fork huggingface's transformers library to improve on code related to language modeling.
