### ISSUE TITLE
why do you train only 12.5 K steps?

### ISSUE THREAD

**Issue by shizhediao** [allenai/dont-stop-pretraining#14]
Any justifications?

**Comment by kyleclo** [comment]
Mostly based off intuition.  We wanted to train for long enough where the resulting model would be reasonably "within distribution" such that we could study the phenomena of interest, but we also don't have infinite data & budget to keep training or try a lot of different amounts of steps.  

100k updates at batch size of 256 seemed sensible based on informal past domain adaptation experiments.  But we also found the RoBERTa paper recommended using extremely large batch sizes (e.g. 2048), so we just converted that to 100K * 256 / 2048 = 12.5K updates.

**Comment by shizhediao** [comment]
ok, got it. Thanks!
