### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by shizhediao** [allenai/dont-stop-pretraining#15]
When I run the DAPT, MemoryError occurs.
It seems that it runs out of my memory.
My data file is 48GB (biomed) filtered by myself and my memory is 128 GB.
Could you give me some hints for solving this problem?
Thanks!

`File "/import/home/X/dont-stop-pretraining/scripts/run_language_modeling.py", line 133, in load_and_cache_examples
    return LineByLineTextDataset(tokenizer, args, file_path=file_path, block_size=args.block_size)

  File "/import/home/X/dont-stop-pretraining/scripts/run_language_modeling.py", line 119, in __init__
    lines = [line for line in f.read().splitlines() if (len(line) > 0 and not line.isspace())]

  File "/home/X/.conda/envs/domains/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError`

**Comment by kernelmachine** [comment]
hi there, sorry for the delay. It's hard to know what exactly is going on -- I would see if there's any particularly long file in your dataset, or whether your RAM is not large enough to hold the data. Sorry I can't be more helpful!
