### ISSUE TITLE
About RCT dataset

### ISSUE THREAD

**Issue by PrettyMeng** [allenai/dont-stop-pretraining#20]
I notice that in your paper, you mentioned that "for RCT, we represent all sentences in one long sequence for
simultaneous prediction". What do you mean by this? I did not find a specifical treatment when dealing with RCT dataset in your code. 
Looking forward to your reply, Thanks!

**Comment by kernelmachine** [comment]
Hi there, sorry about the delay. This means that we don't do sentence splitting, we just pass the entire document into RoBERTa (up till 512 tokens)
