### ISSUE TITLE
Dataset for DAPT

### ISSUE THREAD

**Issue by seungwon1** [allenai/dont-stop-pretraining#23]
In environments/datasets.py, it seems that datasets for DAPT are missing.

Can you provide external links to download datasets for DAPT?

**Comment by kernelmachine** [comment]
Hi there, sorry about the delay.  We don't have the license to release the DAPT data, but you can look at how to recreate the science DAPT datasets here: https://github.com/allenai/dont-stop-pretraining/issues/4
