### ISSUE TITLE
Regarding MLM Loss of Lrob and Ldapt

### ISSUE THREAD

**Issue by pskadasi** [allenai/dont-stop-pretraining#28]
hi, can you tell me how this Lrob and Ldapt are calculated, coz biomed, cs, news, reviews domains are same for Lrob as well as can be seen from the table

<img width="1103" alt="Screenshot 2021-02-10 at 8 08 22 PM" src="https://user-images.githubusercontent.com/48944276/107902529-b512ee80-6f6c-11eb-8f57-8bbca8a3baa5.png">

**Comment by kernelmachine** [comment]
You can check this folder for this MLM loss study: https://github.com/allenai/dont-stop-pretraining/tree/master/mlm_study
