### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by Nardien** [allenai/dont-stop-pretraining#6]
Hi. First of all, thank you for your great work on task adaptation!

Since I want to do some researches about task adaptation of language model, 

I think that it will be cool if I can use the dataset that you used.

As far as I saw, the s3 link of datasets is set as private, then other people cannot download it.

Am I miss something even if I can download the dataset from the given link?

If not, do you have any plan to open the dataset you used to the public?

As I suppose, I think it may be difficult since some datasets have copyright...

Thank you for reading my issues!

**Comment by kernelmachine** [comment]
Hi there, if you'd like to use the dataset outside of allennlp, you will have to `curl` each `.jsonl` file individually, like so: 

```
curl -Lo train.jsonl https://allennlp.s3-us-west-2.amazonaws.com/dont_stop_pretraining/data/chemprot/train.jsonl
curl -Lo dev.jsonl https://allennlp.s3-us-west-2.amazonaws.com/dont_stop_pretraining/data/chemprot/dev.jsonl
curl -Lo test.jsonl https://allennlp.s3-us-west-2.amazonaws.com/dont_stop_pretraining/data/chemprot/test.jsonl
```

**Comment by Nardien** [comment]
Thanks a lot! :)
