### ISSUE TITLE
IMDB train/dev split

### ISSUE THREAD

**Issue by Hapiny** [allenai/dont-stop-pretraining#7]
How did you split the IMDB dataset into train and dev parts (25.000 -> 20.000 + 5.000)? Is this some kind of standard split or did you randomly split?

**Comment by lshowway** [comment]
> How did you split the IMDB dataset into train and dev parts (25.000 -> 20.000 + 5.000)? Is this some kind of standard split or did you randomly split?

http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz 
it is the link of IMDB dataset.

**Comment by Hapiny** [comment]
You did not answer my question.
The dataset (by your link) contains 25.000 train & 25.000 test samples (additionally 50.000 unlabeled samples).
How did you choose 5.000 samples for DEV part in your experiments with IMDB?

**Comment by kernelmachine** [comment]
Hey there, this is a random split that we used for a previous paper (https://arxiv.org/abs/1906.02242). You can make your own splits if you'd like, there will probably be a minimal amount of noise.
