### ISSUE TITLE
How to use pretrained TAPT with classification head(s)?

### ISSUE THREAD

**Issue by qianc62** [allenai/dont-stop-pretraining#8]
Hi, very impressive work. A quick question, how to use the pretrained TAPT (e.g., allenai/dsp_roberta_base_tapt_chemprot_4169) with the corresponding pretrained classification head? I can only get a sentence embedding via 'all_hidden_states = model(input_ids)'.

**Comment by kernelmachine** [comment]
Hi there, you can use pretrained TAPT with any huggingface transformers classification head (check examples in that repository), or via AllenNLP as we do in this repository. Feel free to reopen if you have any other questions.
